version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    groups:
      youtubedl-android:
        patterns:
          - "io.github.junkfood02.youtubedl-android:*"
      androidx:
        patterns:
          - "androidx.*"
    
