name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build and publish signed APKs
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build release
        run: gradle assembleRelease

      - name: Sign APKs
        id: sign_app
        uses: ilharp/sign-android-release@nightly
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Rename APKs
        run: |
          mv app/build/outputs/apk/release/app-universal-release-unsigned-signed.apk app/build/outputs/omneko-${{ github.ref_name }}-universal-release.apk
          mv app/build/outputs/apk/release/app-x86-release-unsigned-signed.apk app/build/outputs/omneko-${{ github.ref_name }}-x86-release.apk
          mv app/build/outputs/apk/release/app-x86_64-release-unsigned-signed.apk app/build/outputs/omneko-${{ github.ref_name }}-x86_64-release.apk
          mv app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk app/build/outputs/omneko-${{ github.ref_name }}-armeabi-v7a-release.apk
          mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk app/build/outputs/omneko-${{ github.ref_name }}-arm64-v8a-release.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-files
          path: app/build/outputs/*-release.apk
          overwrite: true

      - name: Calculate checksums
        run: |
          checksum=`sha256sum app/build/outputs/omneko-${{ github.ref_name }}-universal-release.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_CHECKSUM=$checksum" >> $GITHUB_ENV

          checksum=`sha256sum app/build/outputs/omneko-${{ github.ref_name }}-x86-release.apk | awk '{ print $1 }'`
          echo "APK_X86_CHECKSUM=$checksum" >> $GITHUB_ENV

          checksum=`sha256sum app/build/outputs/omneko-${{ github.ref_name }}-x86_64-release.apk | awk '{ print $1 }'`
          echo "APK_X86_64_CHECKSUM=$checksum" >> $GITHUB_ENV

          checksum=`sha256sum app/build/outputs/omneko-${{ github.ref_name }}-armeabi-v7a-release.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_CHECKSUM=$checksum" >> $GITHUB_ENV

          checksum=`sha256sum app/build/outputs/omneko-${{ github.ref_name }}-arm64-v8a-release.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_CHECKSUM=$checksum" >> $GITHUB_ENV

      - name: Get changelog info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## Changelog

            ${{ steps.query-release-info.outputs.release-notes }}

            ## Checksums

            | File | SHA-256 |
            | ---- | ------- |
            | omneko-${{ github.ref_name }}-universal-release.apk | ${{ env.APK_UNIVERSAL_CHECKSUM }} |
            | omneko-${{ github.ref_name }}-x86-release.apk | ${{ env.APK_X86_CHECKSUM }} |
            | omneko-${{ github.ref_name }}-x86_64-release.apk | ${{ env.APK_X86_64_CHECKSUM }} |
            | omneko-${{ github.ref_name }}-armeabi-v7a-release.apk | ${{ env.APK_ARMEABI_V7A_CHECKSUM }} |
            | omneko-${{ github.ref_name }}-arm64-v8a-release.apk | ${{ env.APK_ARM64_V8A_CHECKSUM }} |
          draft: true
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          files: |
            app/build/outputs/omneko-${{ github.ref_name }}-universal-release.apk
            app/build/outputs/omneko-${{ github.ref_name }}-x86-release.apk
            app/build/outputs/omneko-${{ github.ref_name }}-x86_64-release.apk
            app/build/outputs/omneko-${{ github.ref_name }}-armeabi-v7a-release.apk
            app/build/outputs/omneko-${{ github.ref_name }}-arm64-v8a-release.apk
        
